server:
  logLevel: 5
  useDevelLog: true
  secretNameAuthToken: ""
  secretNameAuthRSAPublicKey: ""
  securityAllowTable: ""

migrations:
  enabled: false
  configMapName: sqlite-rest-migrations

litestream:
  enabled: false
  image:
    repository: litestream/litestream
    pullPolicy: IfNotPresent
    tag: "0.3.6"
  secretName: sqlite-rest-litestream-config

data:
  enabled: false
  storageClassName: ""
  resource:
    requests:
      storage: "100Mi"

labels:
  build4.fun/app: sqlite-rest

image:
  repository: ghcr.io/b4fun/sqlite-rest/server
  pullPolicy: IfNotPresent
  tag: "main"

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  name: sqlite-rest

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 20Mi

nodeSelector:
  kubernetes.io/os: linux
